services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432:5432'
  fakesmtp:
    image: 'reachfive/fake-smtp-server'
    ports:
      - '1080:1080'
      - '1025:1025'
  spring-boot-app:
    container_name: spring-boot-app
    image: spring-boot-app
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - fakesmtp
    ports:
      - '8080:8080'
    environment:
      - spring_datasource_url=jdbc:postgresql://postgres:5432/mydatabase
      - spring_mail_host=fakesmtp
    restart: always

