services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432:5432'
  fakesmtp:
    image: 'reachfive/fake-smtp-server'
    ports:
      - '1080:1080'
      - '1025:1025'
